/**
 * @packageDocumentation
 * @module api.functional.api.v1.blocks
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import typia from "typia";
import type { tags } from "typia";

import type { AuthProvider } from "../../../../structures/AuthProvider";

/**
 * @controller BlockController.list
 * @path GET /api/v1/blocks
 * @accessor api.functional.api.v1.blocks.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function list(connection: IConnection): Promise<list.Output> {
  return true === connection.simulate
    ? list.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...list.METADATA,
        template: list.METADATA.path,
        path: list.path(),
      });
}
export namespace list {
  export type Output = AuthProvider.User[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/blocks",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/blocks";
  export const random = (): AuthProvider.User[] =>
    typia.random<AuthProvider.User[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * @controller BlockController.create
 * @path POST /api/v1/blocks
 * @accessor api.functional.api.v1.blocks.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Output> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        props.input,
      );
}
export namespace create {
  export type Props = { input: Body };
  export type Body = {
    blocked_id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = { blocked_id: string };

  export const METADATA = {
    method: "POST",
    path: "/api/v1/blocks",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/v1/blocks";
  export const random = (): { blocked_id: string } =>
    typia.random<{ blocked_id: string }>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller BlockController.remove
 * @path DELETE /api/v1/blocks/:userId
 * @accessor api.functional.api.v1.blocks.remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  props: remove.Props,
): Promise<void> {
  return true === connection.simulate
    ? remove.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...remove.METADATA,
        template: remove.METADATA.path,
        path: remove.path(props),
      });
}
export namespace remove {
  export type Props = {
    userId: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/api/v1/blocks/:userId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/blocks/${encodeURIComponent(props.userId?.toString() ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (connection: IConnection, props: Props): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("userId")(() => typia.assert(props.userId));
    return random();
  };
}
