/**
 * @packageDocumentation
 * @module api.functional.api.v1.users.records
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";
import typia from "typia";

import type { AccountProvider } from "../../../../../structures/AccountProvider";

/**
 * @controller AccountController.publicRecords
 * @path GET /api/v1/users/:id/records
 * @accessor api.functional.api.v1.users.records.publicRecords
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function publicRecords(
  connection: IConnection,
  props: publicRecords.Props,
): Promise<publicRecords.Output> {
  return true === connection.simulate
    ? publicRecords.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...publicRecords.METADATA,
        template: publicRecords.METADATA.path,
        path: publicRecords.path(props),
      });
}
export namespace publicRecords {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = AccountProvider.Record[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/users/:id/records",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/users/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/records`;
  export const random = (): AccountProvider.Record[] =>
    typia.random<AccountProvider.Record[]>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}
