/**
 * @packageDocumentation
 * @module api.functional.api.v1.auth.recovery_code
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import typia from "typia";

import type { AuthProvider } from "../../../../../structures/AuthProvider";

/**
 * @controller AuthController.reissue
 * @path POST /api/v1/auth/recovery-code
 * @accessor api.functional.api.v1.auth.recovery_code.reissue
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function reissue(
  connection: IConnection,
  props: reissue.Props,
): Promise<reissue.Output> {
  return true === connection.simulate
    ? reissue.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...reissue.METADATA,
          template: reissue.METADATA.path,
          path: reissue.path(),
        },
        props.input,
      );
}
export namespace reissue {
  export type Props = { input: Body };
  export type Body = AuthProvider.Password;
  export type Output = AuthProvider.RecoveryCode;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/auth/recovery-code",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/auth/recovery-code";
  export const random = (): AuthProvider.RecoveryCode =>
    typia.random<AuthProvider.RecoveryCode>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props.input));
    return random();
  };
}
