/**
 * @packageDocumentation
 * @module api.functional.api.v1.project_invitations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import typia from "typia";
import type { tags } from "typia";

import type { ProjectProvider } from "../../../../structures/ProjectProvider";

/**
 * @controller ProjectInvitationController.list
 * @path GET /api/v1/project-invitations
 * @accessor api.functional.api.v1.project_invitations.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function list(
  connection: IConnection,
  props: list.Props,
): Promise<list.Output> {
  return true === connection.simulate
    ? list.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...list.METADATA,
        template: list.METADATA.path,
        path: list.path(props),
      });
}
export namespace list {
  export type Props = { query: Query };
  export type Query = {
    status?: undefined | "accepted" | "cancelled" | "pending" | "rejected";
  };
  export type Output = ProjectProvider.Invitation[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/project-invitations",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(props.query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/v1/project-invitations";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): ProjectProvider.Invitation[] =>
    typia.random<ProjectProvider.Invitation[]>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.query(() => typia.assert(props.query));
    return random();
  };
}

/**
 * @controller ProjectInvitationController.accept
 * @path POST /api/v1/project-invitations/:id/accept
 * @accessor api.functional.api.v1.project_invitations.accept
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function accept(
  connection: IConnection,
  props: accept.Props,
): Promise<accept.Output> {
  return true === connection.simulate
    ? accept.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...accept.METADATA,
        template: accept.METADATA.path,
        path: accept.path(props),
      });
}
export namespace accept {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = ProjectProvider.Membership;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/project-invitations/:id/accept",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/project-invitations/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/accept`;
  export const random = (): ProjectProvider.Membership =>
    typia.random<ProjectProvider.Membership>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * @controller ProjectInvitationController.reject
 * @path POST /api/v1/project-invitations/:id/reject
 * @accessor api.functional.api.v1.project_invitations.reject
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function reject(
  connection: IConnection,
  props: reject.Props,
): Promise<void> {
  return true === connection.simulate
    ? reject.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...reject.METADATA,
        template: reject.METADATA.path,
        path: reject.path(props),
      });
}
export namespace reject {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };

  export const METADATA = {
    method: "POST",
    path: "/api/v1/project-invitations/:id/reject",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/project-invitations/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/reject`;
  export const random = (): void => typia.random<void>();
  export const simulate = (connection: IConnection, props: Props): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * @controller ProjectInvitationController.cancel
 * @path DELETE /api/v1/project-invitations/:id
 * @accessor api.functional.api.v1.project_invitations.cancel
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function cancel(
  connection: IConnection,
  props: cancel.Props,
): Promise<void> {
  return true === connection.simulate
    ? cancel.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...cancel.METADATA,
        template: cancel.METADATA.path,
        path: cancel.path(props),
      });
}
export namespace cancel {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/api/v1/project-invitations/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/project-invitations/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (connection: IConnection, props: Props): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}
