/**
 * @packageDocumentation
 * @module api.functional.api.v1.workspaces
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";
import typia from "typia";

import type { WorkspaceProvider } from "../../../../structures/WorkspaceProvider";

export * as counters from "./counters/index";
export * as records from "./records/index";
export * as timer from "./timer/index";

/**
 * @controller WorkspaceController.get
 * @path GET /api/v1/workspaces/:id
 * @accessor api.functional.api.v1.workspaces.get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(
  connection: IConnection,
  props: get.Props,
): Promise<get.Output> {
  return true === connection.simulate
    ? get.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...get.METADATA,
        template: get.METADATA.path,
        path: get.path(props),
      });
}
export namespace get {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = WorkspaceProvider.Workspace;

  export const METADATA = {
    method: "GET",
    path: "/api/v1/workspaces/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/workspaces/${encodeURIComponent(props.id?.toString() ?? "null")}`;
  export const random = (): WorkspaceProvider.Workspace =>
    typia.random<WorkspaceProvider.Workspace>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * @controller WorkspaceController.update
 * @path PATCH /api/v1/workspaces/:id
 * @accessor api.functional.api.v1.workspaces.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Output> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          template: update.METADATA.path,
          path: update.path(props),
        },
        props.input,
      );
}
export namespace update {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = WorkspaceProvider.Update;
  export type Output = WorkspaceProvider.Workspace;

  export const METADATA = {
    method: "PATCH",
    path: "/api/v1/workspaces/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/workspaces/${encodeURIComponent(props.id?.toString() ?? "null")}`;
  export const random = (): WorkspaceProvider.Workspace =>
    typia.random<WorkspaceProvider.Workspace>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}
