/**
 * @packageDocumentation
 * @module api.functional.api.v1
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import typia from "typia";

import type { CommunityProvider } from "../../../structures/CommunityProvider";

export * as users from "./users/index";
export * as auth from "./auth/index";
export * as policy_documents from "./policy_documents/index";
export * as projects from "./projects/index";
export * as project_invitations from "./project_invitations/index";
export * as friend_requests from "./friend_requests/index";
export * as friends from "./friends/index";
export * as blocks from "./blocks/index";
export * as workspaces from "./workspaces/index";
export * as counters from "./counters/index";
export * as records from "./records/index";
export * as record_comments from "./record_comments/index";
export * as posts from "./posts/index";
export * as post_comments from "./post_comments/index";
export * as reports from "./reports/index";
export * as admin from "./admin/index";

/**
 * @controller CommunityController.feed
 * @path GET /api/v1/feed
 * @accessor api.functional.api.v1.feed
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function feed(
  connection: IConnection,
  props: feed.Props,
): Promise<feed.Output> {
  return true === connection.simulate
    ? feed.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...feed.METADATA,
        template: feed.METADATA.path,
        path: feed.path(props),
      });
}
export namespace feed {
  export type Props = { query: Query };
  export type Query = CommunityProvider.Query;
  export type Output = CommunityProvider.Feed;

  export const METADATA = {
    method: "GET",
    path: "/api/v1/feed",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(props.query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/v1/feed";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): CommunityProvider.Feed =>
    typia.random<CommunityProvider.Feed>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.query(() => typia.assert(props.query));
    return random();
  };
}
