/**
 * @packageDocumentation
 * @module api.functional.api.v1.auth.recovery
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import typia from "typia";

import type { AuthProvider } from "../../../../../structures/AuthProvider";

/**
 * @controller AuthController.recover
 * @path POST /api/v1/auth/recovery
 * @accessor api.functional.api.v1.auth.recovery.recover
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function recover(
  connection: IConnection,
  props: recover.Props,
): Promise<recover.Output> {
  return true === connection.simulate
    ? recover.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...recover.METADATA,
          template: recover.METADATA.path,
          path: recover.path(),
        },
        props.input,
      );
}
export namespace recover {
  export type Props = { input: Body };
  export type Body = AuthProvider.Recovery;
  export type Output = AuthProvider.RegistrationSession;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/auth/recovery",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/auth/recovery";
  export const random = (): AuthProvider.RegistrationSession =>
    typia.random<AuthProvider.RegistrationSession>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props.input));
    return random();
  };
}
