/**
 * @packageDocumentation
 * @module api.functional.api.v1.projects.members
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";
import typia from "typia";

import type { ProjectProvider } from "../../../../../structures/ProjectProvider";

/**
 * @controller ProjectController.kick
 * @path POST /api/v1/projects/:id/members/:userId/kick
 * @accessor api.functional.api.v1.projects.members.kick
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function kick(
  connection: IConnection,
  props: kick.Props,
): Promise<kick.Output> {
  return true === connection.simulate
    ? kick.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...kick.METADATA,
          template: kick.METADATA.path,
          path: kick.path(props),
        },
        props.input,
      );
}
export namespace kick {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    userId: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = ProjectProvider.Move;
  export type Output = ProjectProvider.Transfer;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/projects/:id/members/:userId/kick",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/projects/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/members/${encodeURIComponent(props.userId?.toString() ?? "null")}/kick`;
  export const random = (): ProjectProvider.Transfer =>
    typia.random<ProjectProvider.Transfer>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.param("userId")(() => typia.assert(props.userId));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}
