/**
 * @packageDocumentation
 * @module api.functional.api.v1.counters
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";
import typia from "typia";

import type { WorkspaceProvider } from "../../../../structures/WorkspaceProvider";

/**
 * @controller CounterController.update
 * @path PATCH /api/v1/counters/:id
 * @accessor api.functional.api.v1.counters.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Output> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          template: update.METADATA.path,
          path: update.path(props),
        },
        props.input,
      );
}
export namespace update {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = WorkspaceProvider.CounterUpdate;
  export type Output = WorkspaceProvider.Counter;

  export const METADATA = {
    method: "PATCH",
    path: "/api/v1/counters/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/counters/${encodeURIComponent(props.id?.toString() ?? "null")}`;
  export const random = (): WorkspaceProvider.Counter =>
    typia.random<WorkspaceProvider.Counter>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller CounterController.adjust
 * @path POST /api/v1/counters/:id/adjust
 * @accessor api.functional.api.v1.counters.adjust
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function adjust(
  connection: IConnection,
  props: adjust.Props,
): Promise<adjust.Output> {
  return true === connection.simulate
    ? adjust.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...adjust.METADATA,
          template: adjust.METADATA.path,
          path: adjust.path(props),
        },
        props.input,
      );
}
export namespace adjust {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = WorkspaceProvider.Adjust;
  export type Output = WorkspaceProvider.Counter;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/counters/:id/adjust",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/counters/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/adjust`;
  export const random = (): WorkspaceProvider.Counter =>
    typia.random<WorkspaceProvider.Counter>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller CounterController.reset
 * @path POST /api/v1/counters/:id/reset
 * @accessor api.functional.api.v1.counters.reset
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function reset(
  connection: IConnection,
  props: reset.Props,
): Promise<reset.Output> {
  return true === connection.simulate
    ? reset.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...reset.METADATA,
          template: reset.METADATA.path,
          path: reset.path(props),
        },
        props.input,
      );
}
export namespace reset {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = WorkspaceProvider.Command;
  export type Output = WorkspaceProvider.Counter;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/counters/:id/reset",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/counters/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/reset`;
  export const random = (): WorkspaceProvider.Counter =>
    typia.random<WorkspaceProvider.Counter>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller CounterController.remove
 * @path DELETE /api/v1/counters/:id
 * @accessor api.functional.api.v1.counters.remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  props: remove.Props,
): Promise<void> {
  return true === connection.simulate
    ? remove.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...remove.METADATA,
          template: remove.METADATA.path,
          path: remove.path(props),
        },
        props.input,
      );
}
export namespace remove {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = WorkspaceProvider.Command;

  export const METADATA = {
    method: "DELETE",
    path: "/api/v1/counters/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/counters/${encodeURIComponent(props.id?.toString() ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (connection: IConnection, props: Props): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}
