/**
 * @packageDocumentation
 * @module api.functional.api.v1.workspaces.counters
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";
import typia from "typia";

import type { WorkspaceProvider } from "../../../../../structures/WorkspaceProvider";

/**
 * @controller WorkspaceController.counters
 * @path GET /api/v1/workspaces/:id/counters
 * @accessor api.functional.api.v1.workspaces.counters.counters
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function counters(
  connection: IConnection,
  props: counters.Props,
): Promise<counters.Output> {
  return true === connection.simulate
    ? counters.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...counters.METADATA,
        template: counters.METADATA.path,
        path: counters.path(props),
      });
}
export namespace counters {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = WorkspaceProvider.Counter[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/workspaces/:id/counters",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/workspaces/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/counters`;
  export const random = (): WorkspaceProvider.Counter[] =>
    typia.random<WorkspaceProvider.Counter[]>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * @controller WorkspaceController.createCounter
 * @path POST /api/v1/workspaces/:id/counters
 * @accessor api.functional.api.v1.workspaces.counters.createCounter
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createCounter(
  connection: IConnection,
  props: createCounter.Props,
): Promise<createCounter.Output> {
  return true === connection.simulate
    ? createCounter.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...createCounter.METADATA,
          template: createCounter.METADATA.path,
          path: createCounter.path(props),
        },
        props.input,
      );
}
export namespace createCounter {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = WorkspaceProvider.CounterCreate;
  export type Output = WorkspaceProvider.Counter;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/workspaces/:id/counters",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/workspaces/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/counters`;
  export const random = (): WorkspaceProvider.Counter =>
    typia.random<WorkspaceProvider.Counter>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller WorkspaceController.order
 * @path PATCH /api/v1/workspaces/:id/counters/order
 * @accessor api.functional.api.v1.workspaces.counters.order
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function order(
  connection: IConnection,
  props: order.Props,
): Promise<order.Output> {
  return true === connection.simulate
    ? order.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...order.METADATA,
          template: order.METADATA.path,
          path: order.path(props),
        },
        props.input,
      );
}
export namespace order {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = WorkspaceProvider.Order;
  export type Output = WorkspaceProvider.Counter[];

  export const METADATA = {
    method: "PATCH",
    path: "/api/v1/workspaces/:id/counters/order",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/workspaces/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/counters/order`;
  export const random = (): WorkspaceProvider.Counter[] =>
    typia.random<WorkspaceProvider.Counter[]>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}
