/**
 * @packageDocumentation
 * @module api.functional.api.v1.admin.reports
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import typia from "typia";
import type { tags } from "typia";

import type { ReportProvider } from "../../../../../structures/ReportProvider";

export * as actions from "./actions/index";

/**
 * @controller ReportOperatorController.queue
 * @path GET /api/v1/admin/reports
 * @accessor api.functional.api.v1.admin.reports.queue
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function queue(
  connection: IConnection,
  props: queue.Props,
): Promise<queue.Output> {
  return true === connection.simulate
    ? queue.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...queue.METADATA,
        template: queue.METADATA.path,
        path: queue.path(props),
      });
}
export namespace queue {
  export type Props = { query: Query };
  export type Query = ReportProvider.OperatorQuery;
  export type Output = ReportProvider.Detail[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/admin/reports",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(props.query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/v1/admin/reports";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): ReportProvider.Detail[] =>
    typia.random<ReportProvider.Detail[]>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.query(() => typia.assert(props.query));
    return random();
  };
}

/**
 * @controller ReportOperatorController.inspect
 * @path GET /api/v1/admin/reports/:id
 * @accessor api.functional.api.v1.admin.reports.inspect
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function inspect(
  connection: IConnection,
  props: inspect.Props,
): Promise<inspect.Output> {
  return true === connection.simulate
    ? inspect.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...inspect.METADATA,
        template: inspect.METADATA.path,
        path: inspect.path(props),
      });
}
export namespace inspect {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = ReportProvider.Detail;

  export const METADATA = {
    method: "GET",
    path: "/api/v1/admin/reports/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/admin/reports/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}`;
  export const random = (): ReportProvider.Detail =>
    typia.random<ReportProvider.Detail>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}
