/**
 * @packageDocumentation
 * @module api.functional.api.v1.records.reactions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";
import typia from "typia";

import type { RecordProvider } from "../../../../../structures/RecordProvider";

/**
 * @controller RecordController.reactions
 * @path GET /api/v1/records/:id/reactions
 * @accessor api.functional.api.v1.records.reactions.reactions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function reactions(
  connection: IConnection,
  props: reactions.Props,
): Promise<reactions.Output> {
  return true === connection.simulate
    ? reactions.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...reactions.METADATA,
        template: reactions.METADATA.path,
        path: reactions.path(props),
      });
}
export namespace reactions {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = RecordProvider.Reaction[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/records/:id/reactions",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/records/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/reactions`;
  export const random = (): RecordProvider.Reaction[] =>
    typia.random<RecordProvider.Reaction[]>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * @controller RecordController.react
 * @path PUT /api/v1/records/:id/reactions/:emoji
 * @accessor api.functional.api.v1.records.reactions.react
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function react(
  connection: IConnection,
  props: react.Props,
): Promise<react.Output> {
  return true === connection.simulate
    ? react.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...react.METADATA,
        template: react.METADATA.path,
        path: react.path(props),
      });
}
export namespace react {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    emoji: string;
  };
  export type Output = RecordProvider.Reaction;

  export const METADATA = {
    method: "PUT",
    path: "/api/v1/records/:id/reactions/:emoji",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/records/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/reactions/${encodeURIComponent(props.emoji?.toString() ?? "null")}`;
  export const random = (): RecordProvider.Reaction =>
    typia.random<RecordProvider.Reaction>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.param("emoji")(() => typia.assert(props.emoji));
    return random();
  };
}

/**
 * @controller RecordController.unreact
 * @path DELETE /api/v1/records/:id/reactions/:emoji
 * @accessor api.functional.api.v1.records.reactions.unreact
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function unreact(
  connection: IConnection,
  props: unreact.Props,
): Promise<void> {
  return true === connection.simulate
    ? unreact.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...unreact.METADATA,
        template: unreact.METADATA.path,
        path: unreact.path(props),
      });
}
export namespace unreact {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    emoji: string;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/api/v1/records/:id/reactions/:emoji",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/records/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/reactions/${encodeURIComponent(props.emoji?.toString() ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (connection: IConnection, props: Props): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.param("emoji")(() => typia.assert(props.emoji));
    return random();
  };
}
