/**
 * @packageDocumentation
 * @module api.functional.api.v1.projects
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import typia from "typia";
import type { tags } from "typia";

import type { ProjectProvider } from "../../../../structures/ProjectProvider";

export * as invitations from "./invitations/index";
export * as members from "./members/index";

/**
 * @controller ProjectController.create
 * @path POST /api/v1/projects
 * @accessor api.functional.api.v1.projects.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Output> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        props.input,
      );
}
export namespace create {
  export type Props = { input: Body };
  export type Body = ProjectProvider.Create;
  export type Output = ProjectProvider.Project;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/projects",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/v1/projects";
  export const random = (): ProjectProvider.Project =>
    typia.random<ProjectProvider.Project>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller ProjectController.list
 * @path GET /api/v1/projects
 * @accessor api.functional.api.v1.projects.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function list(
  connection: IConnection,
  props: list.Props,
): Promise<list.Output> {
  return true === connection.simulate
    ? list.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...list.METADATA,
        template: list.METADATA.path,
        path: list.path(props),
      });
}
export namespace list {
  export type Props = { query: Query };
  export type Query = { status?: undefined | "active" | "done" | "paused" };
  export type Output = ProjectProvider.Project[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/projects",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(props.query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/v1/projects";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): ProjectProvider.Project[] =>
    typia.random<ProjectProvider.Project[]>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.query(() => typia.assert(props.query));
    return random();
  };
}

/**
 * @controller ProjectController.get
 * @path GET /api/v1/projects/:id
 * @accessor api.functional.api.v1.projects.get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(
  connection: IConnection,
  props: get.Props,
): Promise<get.Output> {
  return true === connection.simulate
    ? get.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...get.METADATA,
        template: get.METADATA.path,
        path: get.path(props),
      });
}
export namespace get {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = ProjectProvider.Project;

  export const METADATA = {
    method: "GET",
    path: "/api/v1/projects/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/projects/${encodeURIComponent(props.id?.toString() ?? "null")}`;
  export const random = (): ProjectProvider.Project =>
    typia.random<ProjectProvider.Project>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * @controller ProjectController.update
 * @path PATCH /api/v1/projects/:id
 * @accessor api.functional.api.v1.projects.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Output> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          template: update.METADATA.path,
          path: update.path(props),
        },
        props.input,
      );
}
export namespace update {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = ProjectProvider.Update;
  export type Output = ProjectProvider.Project;

  export const METADATA = {
    method: "PATCH",
    path: "/api/v1/projects/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/projects/${encodeURIComponent(props.id?.toString() ?? "null")}`;
  export const random = (): ProjectProvider.Project =>
    typia.random<ProjectProvider.Project>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller ProjectController.remove
 * @path DELETE /api/v1/projects/:id
 * @accessor api.functional.api.v1.projects.remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  props: remove.Props,
): Promise<void> {
  return true === connection.simulate
    ? remove.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...remove.METADATA,
        template: remove.METADATA.path,
        path: remove.path(props),
      });
}
export namespace remove {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/api/v1/projects/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/projects/${encodeURIComponent(props.id?.toString() ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (connection: IConnection, props: Props): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * @controller ProjectController.memberships
 * @path GET /api/v1/projects/:id/memberships
 * @accessor api.functional.api.v1.projects.memberships
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function memberships(
  connection: IConnection,
  props: memberships.Props,
): Promise<memberships.Output> {
  return true === connection.simulate
    ? memberships.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...memberships.METADATA,
        template: memberships.METADATA.path,
        path: memberships.path(props),
      });
}
export namespace memberships {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = ProjectProvider.Membership[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/projects/:id/memberships",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/projects/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/memberships`;
  export const random = (): ProjectProvider.Membership[] =>
    typia.random<ProjectProvider.Membership[]>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * @controller ProjectController.workspaces
 * @path GET /api/v1/projects/:id/workspaces
 * @accessor api.functional.api.v1.projects.workspaces
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function workspaces(
  connection: IConnection,
  props: workspaces.Props,
): Promise<workspaces.Output> {
  return true === connection.simulate
    ? workspaces.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...workspaces.METADATA,
        template: workspaces.METADATA.path,
        path: workspaces.path(props),
      });
}
export namespace workspaces {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = ProjectProvider.Workspace[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/projects/:id/workspaces",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/projects/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/workspaces`;
  export const random = (): ProjectProvider.Workspace[] =>
    typia.random<ProjectProvider.Workspace[]>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * @controller ProjectController.owner
 * @path PATCH /api/v1/projects/:id/owner
 * @accessor api.functional.api.v1.projects.owner
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function owner(
  connection: IConnection,
  props: owner.Props,
): Promise<owner.Output> {
  return true === connection.simulate
    ? owner.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...owner.METADATA,
          template: owner.METADATA.path,
          path: owner.path(props),
        },
        props.input,
      );
}
export namespace owner {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = {
    owner_user_id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = ProjectProvider.Project;

  export const METADATA = {
    method: "PATCH",
    path: "/api/v1/projects/:id/owner",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/projects/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/owner`;
  export const random = (): ProjectProvider.Project =>
    typia.random<ProjectProvider.Project>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller ProjectController.leave
 * @path POST /api/v1/projects/:id/leave
 * @accessor api.functional.api.v1.projects.leave
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function leave(
  connection: IConnection,
  props: leave.Props,
): Promise<leave.Output> {
  return true === connection.simulate
    ? leave.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...leave.METADATA,
          template: leave.METADATA.path,
          path: leave.path(props),
        },
        props.input,
      );
}
export namespace leave {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = ProjectProvider.Move;
  export type Output = ProjectProvider.Transfer;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/projects/:id/leave",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/projects/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/leave`;
  export const random = (): ProjectProvider.Transfer =>
    typia.random<ProjectProvider.Transfer>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}
