/**
 * @packageDocumentation
 * @module api.functional.api.v1.admin.reports.actions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";
import typia from "typia";

import type { ReportProvider } from "../../../../../../structures/ReportProvider";

/**
 * @controller ReportOperatorController.action
 * @path POST /api/v1/admin/reports/:id/actions
 * @accessor api.functional.api.v1.admin.reports.actions.action
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function action(
  connection: IConnection,
  props: action.Props,
): Promise<action.Output> {
  return true === connection.simulate
    ? action.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...action.METADATA,
          template: action.METADATA.path,
          path: action.path(props),
        },
        props.input,
      );
}
export namespace action {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = ReportProvider.ActionInput;
  export type Output = ReportProvider.Action;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/admin/reports/:id/actions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/admin/reports/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/actions`;
  export const random = (): ReportProvider.Action =>
    typia.random<ReportProvider.Action>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}
