/**
 * @packageDocumentation
 * @module api.functional.api.v1.policy_documents
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import typia from "typia";

import type { PolicyProvider } from "../../../../structures/PolicyProvider";

/**
 * @controller PolicyController.list
 * @path GET /api/v1/policy-documents
 * @accessor api.functional.api.v1.policy_documents.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function list(connection: IConnection): Promise<list.Output> {
  return true === connection.simulate
    ? list.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...list.METADATA,
        template: list.METADATA.path,
        path: list.path(),
      });
}
export namespace list {
  export type Output = PolicyProvider.Document[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/policy-documents",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/policy-documents";
  export const random = (): PolicyProvider.Document[] =>
    typia.random<PolicyProvider.Document[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
