/**
 * @packageDocumentation
 * @module api.functional.api.v1.users.me.policy_consents
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import typia from "typia";

import type { AccountProvider } from "../../../../../../structures/AccountProvider";
import type { PolicyProvider } from "../../../../../../structures/PolicyProvider";

/**
 * @controller AccountController.consents
 * @path GET /api/v1/users/me/policy-consents
 * @accessor api.functional.api.v1.users.me.policy_consents.consents
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function consents(
  connection: IConnection,
): Promise<consents.Output> {
  return true === connection.simulate
    ? consents.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...consents.METADATA,
        template: consents.METADATA.path,
        path: consents.path(),
      });
}
export namespace consents {
  export type Output = PolicyProvider.Consent[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/users/me/policy-consents",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/users/me/policy-consents";
  export const random = (): PolicyProvider.Consent[] =>
    typia.random<PolicyProvider.Consent[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * @controller AccountController.agree
 * @path POST /api/v1/users/me/policy-consents
 * @accessor api.functional.api.v1.users.me.policy_consents.agree
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function agree(
  connection: IConnection,
  props: agree.Props,
): Promise<agree.Output> {
  return true === connection.simulate
    ? agree.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...agree.METADATA,
          template: agree.METADATA.path,
          path: agree.path(),
        },
        props.input,
      );
}
export namespace agree {
  export type Props = { input: Body };
  export type Body = AccountProvider.PolicyConsentInput;
  export type Output = PolicyProvider.Consent[];

  export const METADATA = {
    method: "POST",
    path: "/api/v1/users/me/policy-consents",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/users/me/policy-consents";
  export const random = (): PolicyProvider.Consent[] =>
    typia.random<PolicyProvider.Consent[]>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props.input));
    return random();
  };
}
