/**
 * @packageDocumentation
 * @module api.functional.api.v1.reports
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import typia from "typia";

import type { ReportProvider } from "../../../../structures/ReportProvider";

/**
 * @controller ReportController.create
 * @path POST /api/v1/reports
 * @accessor api.functional.api.v1.reports.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Output> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        props.input,
      );
}
export namespace create {
  export type Props = { input: Body };
  export type Body = ReportProvider.Input;
  export type Output = ReportProvider.Receipt;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/reports",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/v1/reports";
  export const random = (): ReportProvider.Receipt =>
    typia.random<ReportProvider.Receipt>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props.input));
    return random();
  };
}
