/**
 * @packageDocumentation
 * @module api.functional.api.v1.posts.comments
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";
import typia from "typia";

import type { CommunityProvider } from "../../../../../structures/CommunityProvider";

/**
 * @controller CommunityController.comments
 * @path GET /api/v1/posts/:id/comments
 * @accessor api.functional.api.v1.posts.comments.comments
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function comments(
  connection: IConnection,
  props: comments.Props,
): Promise<comments.Output> {
  return true === connection.simulate
    ? comments.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...comments.METADATA,
        template: comments.METADATA.path,
        path: comments.path(props),
      });
}
export namespace comments {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = CommunityProvider.Comment[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/posts/:id/comments",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/posts/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/comments`;
  export const random = (): CommunityProvider.Comment[] =>
    typia.random<CommunityProvider.Comment[]>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * @controller CommunityController.comment
 * @path POST /api/v1/posts/:id/comments
 * @accessor api.functional.api.v1.posts.comments.comment
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function comment(
  connection: IConnection,
  props: comment.Props,
): Promise<comment.Output> {
  return true === connection.simulate
    ? comment.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...comment.METADATA,
          template: comment.METADATA.path,
          path: comment.path(props),
        },
        props.input,
      );
}
export namespace comment {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = CommunityProvider.Body;
  export type Output = CommunityProvider.Comment;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/posts/:id/comments",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/posts/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/comments`;
  export const random = (): CommunityProvider.Comment =>
    typia.random<CommunityProvider.Comment>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}
