/**
 * @packageDocumentation
 * @module api.functional.api.v1.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import typia from "typia";

import type { AuthProvider } from "../../../../structures/AuthProvider";

export * as recovery from "./recovery/index";
export * as recovery_code from "./recovery_code/index";

/**
 * @controller AuthController.register
 * @path POST /api/v1/auth/register
 * @accessor api.functional.api.v1.auth.register
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function register(
  connection: IConnection,
  props: register.Props,
): Promise<register.Output> {
  return true === connection.simulate
    ? register.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...register.METADATA,
          template: register.METADATA.path,
          path: register.path(),
        },
        props.input,
      );
}
export namespace register {
  export type Props = { input: Body };
  export type Body = AuthProvider.Registration;
  export type Output = AuthProvider.RegistrationSession;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/auth/register",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/v1/auth/register";
  export const random = (): AuthProvider.RegistrationSession =>
    typia.random<AuthProvider.RegistrationSession>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller AuthController.login
 * @path POST /api/v1/auth/login
 * @accessor api.functional.api.v1.auth.login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function login(
  connection: IConnection,
  props: login.Props,
): Promise<login.Output> {
  return true === connection.simulate
    ? login.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...login.METADATA,
          template: login.METADATA.path,
          path: login.path(),
        },
        props.input,
      );
}
export namespace login {
  export type Props = { input: Body };
  export type Body = AuthProvider.Login;
  export type Output = AuthProvider.Session;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/auth/login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/auth/login";
  export const random = (): AuthProvider.Session =>
    typia.random<AuthProvider.Session>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller AuthController.refresh
 * @path POST /api/v1/auth/refresh
 * @accessor api.functional.api.v1.auth.refresh
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function refresh(
  connection: IConnection,
  props: refresh.Props,
): Promise<refresh.Output> {
  return true === connection.simulate
    ? refresh.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...refresh.METADATA,
          template: refresh.METADATA.path,
          path: refresh.path(),
        },
        props.input,
      );
}
export namespace refresh {
  export type Props = { input: Body };
  export type Body = AuthProvider.Refresh;
  export type Output = AuthProvider.Session;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/auth/refresh",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/auth/refresh";
  export const random = (): AuthProvider.Session =>
    typia.random<AuthProvider.Session>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller AuthController.logout
 * @path POST /api/v1/auth/logout
 * @accessor api.functional.api.v1.auth.logout
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function logout(
  connection: IConnection,
  props: logout.Props,
): Promise<void> {
  return true === connection.simulate
    ? logout.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...logout.METADATA,
          template: logout.METADATA.path,
          path: logout.path(),
        },
        props.input,
      );
}
export namespace logout {
  export type Props = { input: Body };
  export type Body = AuthProvider.Refresh;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/auth/logout",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = () => "/api/v1/auth/logout";
  export const random = (): void => typia.random<void>();
  export const simulate = (connection: IConnection, props: Props): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props.input));
    return random();
  };
}
