/**
 * @packageDocumentation
 * @module api.functional.api.v1.post_comments
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";
import typia from "typia";

/**
 * @controller CommunityController.removeComment
 * @path DELETE /api/v1/post-comments/:id
 * @accessor api.functional.api.v1.post_comments.removeComment
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function removeComment(
  connection: IConnection,
  props: removeComment.Props,
): Promise<void> {
  return true === connection.simulate
    ? removeComment.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...removeComment.METADATA,
        template: removeComment.METADATA.path,
        path: removeComment.path(props),
      });
}
export namespace removeComment {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/api/v1/post-comments/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/post-comments/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (connection: IConnection, props: Props): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}
