/**
 * @packageDocumentation
 * @module api.functional.api.v1.workspaces.records
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";
import typia from "typia";

import type { RecordProvider } from "../../../../../structures/RecordProvider";

/**
 * @controller WorkspaceController.records
 * @path GET /api/v1/workspaces/:id/records
 * @accessor api.functional.api.v1.workspaces.records.records
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function records(
  connection: IConnection,
  props: records.Props,
): Promise<records.Output> {
  return true === connection.simulate
    ? records.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...records.METADATA,
        template: records.METADATA.path,
        path: records.path(props),
      });
}
export namespace records {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = RecordProvider.Record[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/workspaces/:id/records",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/workspaces/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/records`;
  export const random = (): RecordProvider.Record[] =>
    typia.random<RecordProvider.Record[]>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * @controller WorkspaceController.createRecord
 * @path POST /api/v1/workspaces/:id/records
 * @accessor api.functional.api.v1.workspaces.records.createRecord
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createRecord(
  connection: IConnection,
  props: createRecord.Props,
): Promise<createRecord.Output> {
  return true === connection.simulate
    ? createRecord.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...createRecord.METADATA,
          template: createRecord.METADATA.path,
          path: createRecord.path(props),
        },
        props.input,
      );
}
export namespace createRecord {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = RecordProvider.Create;
  export type Output = RecordProvider.Record;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/workspaces/:id/records",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/workspaces/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/records`;
  export const random = (): RecordProvider.Record =>
    typia.random<RecordProvider.Record>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}
