/**
 * @packageDocumentation
 * @module api.functional.api.v1.users
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import typia from "typia";
import type { tags } from "typia";

import type { AuthProvider } from "../../../../structures/AuthProvider";

export * as me from "./me/index";
export * as records from "./records/index";
export * as statistics from "./statistics/index";
export * as posts from "./posts/index";

/**
 * @controller AccountController.search
 * @path GET /api/v1/users
 * @accessor api.functional.api.v1.users.search
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function search(
  connection: IConnection,
  props: search.Props,
): Promise<search.Output> {
  return true === connection.simulate
    ? search.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...search.METADATA,
        template: search.METADATA.path,
        path: search.path(props),
      });
}
export namespace search {
  export type Props = { query: Query };
  export type Query = { query?: undefined | string };
  export type Output = AuthProvider.User[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/users",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(props.query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/v1/users";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): AuthProvider.User[] =>
    typia.random<AuthProvider.User[]>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.query(() => typia.assert(props.query));
    return random();
  };
}

/**
 * @controller AccountController.profile
 * @path GET /api/v1/users/:id
 * @accessor api.functional.api.v1.users.profile
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function profile(
  connection: IConnection,
  props: profile.Props,
): Promise<profile.Output> {
  return true === connection.simulate
    ? profile.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...profile.METADATA,
        template: profile.METADATA.path,
        path: profile.path(props),
      });
}
export namespace profile {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = AuthProvider.User;

  export const METADATA = {
    method: "GET",
    path: "/api/v1/users/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/users/${encodeURIComponent(props.id?.toString() ?? "null")}`;
  export const random = (): AuthProvider.User =>
    typia.random<AuthProvider.User>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}
