/**
 * @packageDocumentation
 * @module api.functional.api.v1.users.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import typia from "typia";

import type { AccountProvider } from "../../../../../structures/AccountProvider";
import type { AuthProvider } from "../../../../../structures/AuthProvider";

export * as policy_consents from "./policy_consents/index";
export * as memberships from "./memberships/index";

/**
 * @controller AccountController.me
 * @path GET /api/v1/users/me
 * @accessor api.functional.api.v1.users.me.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function me(connection: IConnection): Promise<me.Output> {
  return true === connection.simulate
    ? me.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...me.METADATA,
        template: me.METADATA.path,
        path: me.path(),
      });
}
export namespace me {
  export type Output = AuthProvider.User;

  export const METADATA = {
    method: "GET",
    path: "/api/v1/users/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/users/me";
  export const random = (): AuthProvider.User =>
    typia.random<AuthProvider.User>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * @controller AccountController.update
 * @path PATCH /api/v1/users/me
 * @accessor api.functional.api.v1.users.me.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Output> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          template: update.METADATA.path,
          path: update.path(),
        },
        props.input,
      );
}
export namespace update {
  export type Props = { input: Body };
  export type Body = AccountProvider.Update;
  export type Output = AuthProvider.User;

  export const METADATA = {
    method: "PATCH",
    path: "/api/v1/users/me",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/users/me";
  export const random = (): AuthProvider.User =>
    typia.random<AuthProvider.User>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller AccountController.withdraw
 * @path DELETE /api/v1/users/me
 * @accessor api.functional.api.v1.users.me.withdraw
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function withdraw(connection: IConnection): Promise<void> {
  return true === connection.simulate
    ? withdraw.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...withdraw.METADATA,
        template: withdraw.METADATA.path,
        path: withdraw.path(),
      });
}
export namespace withdraw {
  export const METADATA = {
    method: "DELETE",
    path: "/api/v1/users/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = () => "/api/v1/users/me";
  export const random = (): void => typia.random<void>();
  export const simulate = (_connection: IConnection): void => {
    return random();
  };
}

/**
 * @controller AccountController.records
 * @path GET /api/v1/users/me/records
 * @accessor api.functional.api.v1.users.me.records
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function records(
  connection: IConnection,
): Promise<records.Output> {
  return true === connection.simulate
    ? records.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...records.METADATA,
        template: records.METADATA.path,
        path: records.path(),
      });
}
export namespace records {
  export type Output = AccountProvider.Record[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/users/me/records",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/users/me/records";
  export const random = (): AccountProvider.Record[] =>
    typia.random<AccountProvider.Record[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * @controller AccountController.statistics
 * @path GET /api/v1/users/me/statistics
 * @accessor api.functional.api.v1.users.me.statistics
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function statistics(
  connection: IConnection,
): Promise<statistics.Output> {
  return true === connection.simulate
    ? statistics.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...statistics.METADATA,
        template: statistics.METADATA.path,
        path: statistics.path(),
      });
}
export namespace statistics {
  export type Output = AccountProvider.Statistics;

  export const METADATA = {
    method: "GET",
    path: "/api/v1/users/me/statistics",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/users/me/statistics";
  export const random = (): AccountProvider.Statistics =>
    typia.random<AccountProvider.Statistics>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
