/**
 * @packageDocumentation
 * @module api.functional.api.v1.projects.invitations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";
import typia from "typia";

import type { ProjectProvider } from "../../../../../structures/ProjectProvider";

/**
 * @controller ProjectController.invite
 * @path POST /api/v1/projects/:id/invitations
 * @accessor api.functional.api.v1.projects.invitations.invite
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function invite(
  connection: IConnection,
  props: invite.Props,
): Promise<invite.Output> {
  return true === connection.simulate
    ? invite.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...invite.METADATA,
          template: invite.METADATA.path,
          path: invite.path(props),
        },
        props.input,
      );
}
export namespace invite {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = {
    recipient_id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = ProjectProvider.Invitation;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/projects/:id/invitations",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/projects/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/invitations`;
  export const random = (): ProjectProvider.Invitation =>
    typia.random<ProjectProvider.Invitation>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}
