/**
 * @packageDocumentation
 * @module api.functional.api.v1.workspaces.timer
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";
import typia from "typia";

import type { _WorkspaceController } from "../../../../../structures/_WorkspaceController";
import type { RecordProvider } from "../../../../../structures/RecordProvider";
import type { WorkspaceController } from "../../../../../structures/WorkspaceController";
import type { WorkspaceProvider } from "../../../../../structures/WorkspaceProvider";

/**
 * @controller WorkspaceController.timer
 * @path GET /api/v1/workspaces/:id/timer
 * @accessor api.functional.api.v1.workspaces.timer.timer
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function timer(
  connection: IConnection,
  props: timer.Props,
): Promise<timer.Output> {
  return true === connection.simulate
    ? timer.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...timer.METADATA,
        template: timer.METADATA.path,
        path: timer.path(props),
      });
}
export namespace timer {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = null | WorkspaceController.WorkspaceProvider.Timer;

  export const METADATA = {
    method: "GET",
    path: "/api/v1/workspaces/:id/timer",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/workspaces/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/timer`;
  export const random =
    (): null | WorkspaceController.WorkspaceProvider.Timer =>
      typia.random<null | WorkspaceController.WorkspaceProvider.Timer>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * @controller WorkspaceController.start
 * @path POST /api/v1/workspaces/:id/timer/start
 * @accessor api.functional.api.v1.workspaces.timer.start
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function start(
  connection: IConnection,
  props: start.Props,
): Promise<start.Output> {
  return true === connection.simulate
    ? start.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...start.METADATA,
          template: start.METADATA.path,
          path: start.path(props),
        },
        props.input,
      );
}
export namespace start {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = WorkspaceProvider.Command;
  export type Output = _WorkspaceController.WorkspaceProvider.Timer;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/workspaces/:id/timer/start",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/workspaces/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/timer/start`;
  export const random = (): _WorkspaceController.WorkspaceProvider.Timer =>
    typia.random<_WorkspaceController.WorkspaceProvider.Timer>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller WorkspaceController.pause
 * @path POST /api/v1/workspaces/:id/timer/pause
 * @accessor api.functional.api.v1.workspaces.timer.pause
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function pause(
  connection: IConnection,
  props: pause.Props,
): Promise<pause.Output> {
  return true === connection.simulate
    ? pause.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...pause.METADATA,
          template: pause.METADATA.path,
          path: pause.path(props),
        },
        props.input,
      );
}
export namespace pause {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = WorkspaceProvider.Command;
  export type Output = _WorkspaceController.WorkspaceProvider.Timer;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/workspaces/:id/timer/pause",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/workspaces/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/timer/pause`;
  export const random = (): _WorkspaceController.WorkspaceProvider.Timer =>
    typia.random<_WorkspaceController.WorkspaceProvider.Timer>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller WorkspaceController.resume
 * @path POST /api/v1/workspaces/:id/timer/resume
 * @accessor api.functional.api.v1.workspaces.timer.resume
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function resume(
  connection: IConnection,
  props: resume.Props,
): Promise<resume.Output> {
  return true === connection.simulate
    ? resume.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...resume.METADATA,
          template: resume.METADATA.path,
          path: resume.path(props),
        },
        props.input,
      );
}
export namespace resume {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = WorkspaceProvider.Command;
  export type Output = _WorkspaceController.WorkspaceProvider.Timer;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/workspaces/:id/timer/resume",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/workspaces/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/timer/resume`;
  export const random = (): _WorkspaceController.WorkspaceProvider.Timer =>
    typia.random<_WorkspaceController.WorkspaceProvider.Timer>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller WorkspaceController.stop
 * @path POST /api/v1/workspaces/:id/timer/stop
 * @accessor api.functional.api.v1.workspaces.timer.stop
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function stop(
  connection: IConnection,
  props: stop.Props,
): Promise<stop.Output> {
  return true === connection.simulate
    ? stop.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...stop.METADATA,
          template: stop.METADATA.path,
          path: stop.path(props),
        },
        props.input,
      );
}
export namespace stop {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
    input: Body;
  };
  export type Body = WorkspaceProvider.Stop;
  export type Output = RecordProvider.Record;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/workspaces/:id/timer/stop",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (props: Omit<Props, "input">) =>
    `/api/v1/workspaces/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/timer/stop`;
  export const random = (): RecordProvider.Record =>
    typia.random<RecordProvider.Record>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.input));
    return random();
  };
}
