/**
 * @packageDocumentation
 * @module api.functional.api.v1.posts.likes
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";
import typia from "typia";

import type { CommunityProvider } from "../../../../../structures/CommunityProvider";

/**
 * @controller CommunityController.like
 * @path PUT /api/v1/posts/:id/likes
 * @accessor api.functional.api.v1.posts.likes.like
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function like(
  connection: IConnection,
  props: like.Props,
): Promise<like.Output> {
  return true === connection.simulate
    ? like.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...like.METADATA,
        template: like.METADATA.path,
        path: like.path(props),
      });
}
export namespace like {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = CommunityProvider.Like;

  export const METADATA = {
    method: "PUT",
    path: "/api/v1/posts/:id/likes",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/posts/${encodeURIComponent(props.id?.toString() ?? "null")}/likes`;
  export const random = (): CommunityProvider.Like =>
    typia.random<CommunityProvider.Like>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * @controller CommunityController.unlike
 * @path DELETE /api/v1/posts/:id/likes
 * @accessor api.functional.api.v1.posts.likes.unlike
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function unlike(
  connection: IConnection,
  props: unlike.Props,
): Promise<void> {
  return true === connection.simulate
    ? unlike.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...unlike.METADATA,
        template: unlike.METADATA.path,
        path: unlike.path(props),
      });
}
export namespace unlike {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/api/v1/posts/:id/likes",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/posts/${encodeURIComponent(props.id?.toString() ?? "null")}/likes`;
  export const random = (): void => typia.random<void>();
  export const simulate = (connection: IConnection, props: Props): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}
