/**
 * @packageDocumentation
 * @module api.functional.api.v1.users.me.memberships
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import typia from "typia";

import type { AccountProvider } from "../../../../../../structures/AccountProvider";
import type { ProjectProvider } from "../../../../../../structures/ProjectProvider";

/**
 * @controller AccountController.memberships
 * @path GET /api/v1/users/me/memberships
 * @accessor api.functional.api.v1.users.me.memberships.memberships
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function memberships(
  connection: IConnection,
): Promise<memberships.Output> {
  return true === connection.simulate
    ? memberships.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...memberships.METADATA,
        template: memberships.METADATA.path,
        path: memberships.path(),
      });
}
export namespace memberships {
  export type Output = AccountProvider.Membership[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/users/me/memberships",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/users/me/memberships";
  export const random = (): AccountProvider.Membership[] =>
    typia.random<AccountProvider.Membership[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * @controller MembershipHistoryController.get
 * @path GET /api/v1/users/me/memberships
 * @accessor api.functional.api.v1.users.me.memberships.get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(connection: IConnection): Promise<get.Output> {
  return true === connection.simulate
    ? get.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...get.METADATA,
        template: get.METADATA.path,
        path: get.path(),
      });
}
export namespace get {
  export type Output = ProjectProvider.Membership[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/users/me/memberships",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/users/me/memberships";
  export const random = (): ProjectProvider.Membership[] =>
    typia.random<ProjectProvider.Membership[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
