/**
 * @packageDocumentation
 * @module api.functional.api.v1.users.posts
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";
import typia from "typia";

import type { CommunityProvider } from "../../../../../structures/CommunityProvider";

/**
 * @controller CommunityController.byUser
 * @path GET /api/v1/users/:id/posts
 * @accessor api.functional.api.v1.users.posts.byUser
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function byUser(
  connection: IConnection,
  props: byUser.Props,
): Promise<byUser.Output> {
  return true === connection.simulate
    ? byUser.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...byUser.METADATA,
        template: byUser.METADATA.path,
        path: byUser.path(props),
      });
}
export namespace byUser {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = CommunityProvider.Post[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/users/:id/posts",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/users/${encodeURIComponent(props.id?.toString() ?? "null")}/posts`;
  export const random = (): CommunityProvider.Post[] =>
    typia.random<CommunityProvider.Post[]>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}
