/**
 * @packageDocumentation
 * @module api.functional.api.v1.friend_requests
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import typia from "typia";
import type { tags } from "typia";

import type { SocialProvider } from "../../../../structures/SocialProvider";

/**
 * @controller FriendRequestController.list
 * @path GET /api/v1/friend-requests
 * @accessor api.functional.api.v1.friend_requests.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function list(
  connection: IConnection,
  props: list.Props,
): Promise<list.Output> {
  return true === connection.simulate
    ? list.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...list.METADATA,
        template: list.METADATA.path,
        path: list.path(props),
      });
}
export namespace list {
  export type Props = { query: Query };
  export type Query = {
    direction?: undefined | "received" | "sent";
    status?: undefined | "accepted" | "cancelled" | "pending" | "rejected";
  };
  export type Output = SocialProvider.Request[];

  export const METADATA = {
    method: "GET",
    path: "/api/v1/friend-requests",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(props.query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/v1/friend-requests";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): SocialProvider.Request[] =>
    typia.random<SocialProvider.Request[]>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.query(() => typia.assert(props.query));
    return random();
  };
}

/**
 * @controller FriendRequestController.badge
 * @path GET /api/v1/friend-requests/badge
 * @accessor api.functional.api.v1.friend_requests.badge
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function badge(connection: IConnection): Promise<badge.Output> {
  return true === connection.simulate
    ? badge.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...badge.METADATA,
        template: badge.METADATA.path,
        path: badge.path(),
      });
}
export namespace badge {
  export type Output = { pending_count: number };

  export const METADATA = {
    method: "GET",
    path: "/api/v1/friend-requests/badge",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/friend-requests/badge";
  export const random = (): { pending_count: number } =>
    typia.random<{ pending_count: number }>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * @controller FriendRequestController.create
 * @path POST /api/v1/friend-requests
 * @accessor api.functional.api.v1.friend_requests.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Output> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        props.input,
      );
}
export namespace create {
  export type Props = { input: Body };
  export type Body = {
    recipient_id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = SocialProvider.Request;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/friend-requests",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/v1/friend-requests";
  export const random = (): SocialProvider.Request =>
    typia.random<SocialProvider.Request>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props.input));
    return random();
  };
}

/**
 * @controller FriendRequestController.accept
 * @path POST /api/v1/friend-requests/:id/accept
 * @accessor api.functional.api.v1.friend_requests.accept
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function accept(
  connection: IConnection,
  props: accept.Props,
): Promise<accept.Output> {
  return true === connection.simulate
    ? accept.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...accept.METADATA,
        template: accept.METADATA.path,
        path: accept.path(props),
      });
}
export namespace accept {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = SocialProvider.Request;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/friend-requests/:id/accept",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/friend-requests/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/accept`;
  export const random = (): SocialProvider.Request =>
    typia.random<SocialProvider.Request>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * @controller FriendRequestController.reject
 * @path POST /api/v1/friend-requests/:id/reject
 * @accessor api.functional.api.v1.friend_requests.reject
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function reject(
  connection: IConnection,
  props: reject.Props,
): Promise<reject.Output> {
  return true === connection.simulate
    ? reject.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...reject.METADATA,
        template: reject.METADATA.path,
        path: reject.path(props),
      });
}
export namespace reject {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };
  export type Output = SocialProvider.Request;

  export const METADATA = {
    method: "POST",
    path: "/api/v1/friend-requests/:id/reject",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/friend-requests/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}/reject`;
  export const random = (): SocialProvider.Request =>
    typia.random<SocialProvider.Request>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * @controller FriendRequestController.cancel
 * @path DELETE /api/v1/friend-requests/:id
 * @accessor api.functional.api.v1.friend_requests.cancel
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function cancel(
  connection: IConnection,
  props: cancel.Props,
): Promise<void> {
  return true === connection.simulate
    ? cancel.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...cancel.METADATA,
        template: cancel.METADATA.path,
        path: cancel.path(props),
      });
}
export namespace cancel {
  export type Props = {
    id: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/api/v1/friend-requests/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (props: Props) =>
    `/api/v1/friend-requests/${encodeURIComponent(
      props.id?.toString() ?? "null",
    )}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (connection: IConnection, props: Props): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}
